version: '3'
services:
  nginx: 
    image: nginx:latest
    hostname: nginx
    container_name: docker-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/cache/:/etc/nginx/cache
      - ./nginx/cert/:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443

  jenkins:
    image: jenkins:latest
    hostname: jenkins
    container_name: docker-jenkins
    restart: always
    expose:
      - "8080"

